import json
import subprocess
import sys
import threading
import time
import webbrowser
from pathlib import Path
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import parse_qs

PORT = 8765

SUCCESS_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Your door is ready — Finding Your Neighborhood</title>
<style>
body {{
    font-family: Georgia, serif;
    max-width: 820px;
    margin: auto;
    padding: 2rem;
    background: #111;
    color: #eee;
    line-height: 1.7;
}}
h1 {{
    color: #c9a84c;
    margin-bottom: 1rem;
}}
p {{
    color: #bbb;
    margin-bottom: 1rem;
}}
.path {{
    font-family: monospace;
    background: #181818;
    border: 1px solid #444;
    padding: 0.5rem 0.75rem;
    color: #c9a84c;
    display: inline-block;
    margin: 0.5rem 0;
    word-break: break-all;
}}
.note {{
    margin-top: 2rem;
    border-top: 1px solid #444;
    padding-top: 1rem;
    font-size: 0.9rem;
    color: #888;
}}
</style>
</head>
<body>
<h1>Your door is ready.</h1>
<p>It says exactly what you told it to say, points exactly where you want people to go, and collects nothing about anyone who visits.</p>
<p>Your site files are in:</p>
<div class="path">{preview_path}</div>
<p>Open <strong>index.html</strong> in a browser to preview. When you're happy with it, push the <strong>docs/</strong> folder to GitHub Pages to publish.</p>
<div class="note">
    <p>No tracking. No data collected. Static site generated by Finding Your Neighborhood.</p>
</div>
</body>
</html>
"""


def load_existing_config():
    """Load config.json if it exists. Returns a dict of pre-fill values or empty dict."""
    config_path = Path("config.json")
    if not config_path.exists():
        return {}
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
        site = config.get("site", {})
        pages = config.get("pages", [])

        # Find home page and links page
        home = next((p for p in pages if p.get("slug") == "index"), {})
        links_page = next((p for p in pages if p.get("slug") == "links"), {})

        # Flatten links from link_groups
        all_links = []
        for group in links_page.get("link_groups", []):
            all_links.extend(group.get("links", []))
        # Also handle flat links list
        all_links.extend(links_page.get("links", []))

        return {
            "site_title": site.get("title", ""),
            "site_description": site.get("description", ""),
            "theme": site.get("theme", "dark"),
            "home_intro": home.get("intro", ""),
            "home_body": " ".join(home.get("body", [])),
            "links": all_links,
        }
    except Exception:
        return {}


def e(value):
    """HTML-escape a value for safe insertion into form fields."""
    from html import escape
    return escape(str(value), quote=True)


def build_form_html(existing):
    """Build the full form HTML, pre-populated with existing config values if present."""
    site_title = e(existing.get("site_title", ""))
    site_description = e(existing.get("site_description", ""))
    theme = existing.get("theme", "dark")
    home_intro = e(existing.get("home_intro", ""))
    home_body = e(existing.get("home_body", ""))
    links = existing.get("links", [])

    dark_checked = 'checked' if theme != "light" else ''
    light_checked = 'checked' if theme == "light" else ''

    editing_notice = ""
    if existing:
        editing_notice = """
        <div style="background: #1a1a1a; border: 1px solid #c9a84c; padding: 0.75rem 1rem;
                    margin-bottom: 1.5rem; font-size: 0.9rem; color: #bbb;">
            Editing your existing door. Changes will rebuild and replace the current site.
        </div>
        """

    # Build link blocks HTML
    link_blocks = ""
    num_links = max(len(links), 2)
    for i, link in enumerate(links, 1):
        label = e(link.get("label", ""))
        url = e(link.get("url", ""))
        desc = e(link.get("description", ""))
        link_blocks += f"""
    <div class="link-block">
        <h3>Place {i}</h3>
        <label>What is this place?</label>
        <input type="text" name="link_label_{i}" value="{label}" {"required" if i == 1 else ""}>
        <label>Where can someone find it?</label>
        <input type="url" name="link_url_{i}" value="{url}" {"required" if i == 1 else ""}>
        <label>Why would someone go here?</label>
        <textarea name="link_desc_{i}">{desc}</textarea>
        {"" if i <= 2 else '<button type="button" class="secondary remove-link" style="margin-top:0.5rem;">Remove this place</button>'}
    </div>
"""
    # If fewer than 2 links existed, fill remaining blank slots
    for i in range(len(links) + 1, num_links + 1):
        link_blocks += f"""
    <div class="link-block">
        <h3>Place {i}</h3>
        <label>What is this place?</label>
        <input type="text" name="link_label_{i}">
        <label>Where can someone find it?</label>
        <input type="url" name="link_url_{i}">
        <label>Why would someone go here?</label>
        <textarea name="link_desc_{i}"></textarea>
    </div>
"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Finding Your Neighborhood Creator</title>
<style>
body {{
    font-family: Georgia, serif;
    max-width: 820px;
    margin: auto;
    padding: 2rem;
    background: #111;
    color: #eee;
    line-height: 1.6;
}}
h1, h2 {{ color: #c9a84c; }}
.section {{
    border-top: 1px solid #444;
    padding-top: 1.5rem;
    margin-top: 2rem;
}}
label {{
    display: block;
    font-weight: bold;
    margin-top: 1rem;
}}
.help {{
    color: #bbb;
    font-size: 0.9rem;
    margin: 0.25rem 0 0.5rem;
}}
input, textarea {{
    width: 100%;
    padding: .7rem;
    margin-top: .25rem;
    margin-bottom: .75rem;
    font-family: inherit;
    font-size: 1rem;
    background: #181818;
    color: #eee;
    border: 1px solid #444;
}}
input:focus, textarea:focus {{
    outline: 2px solid #c9a84c;
    outline-offset: 1px;
}}
textarea {{ min-height: 90px; }}
.link-block {{
    border: 1px solid #444;
    padding: 1rem;
    margin-top: 1rem;
    background: #181818;
}}
button {{
    padding: .75rem 1.2rem;
    cursor: pointer;
    margin-top: 1rem;
    font-family: Georgia, serif;
    font-size: 1rem;
}}
button[type="submit"] {{
    background: #c9a84c;
    color: #111;
    border: none;
    padding: .85rem 2rem;
}}
button[type="submit"]:hover {{ background: #e0bc6a; }}
button.secondary {{
    background: #222;
    color: #eee;
    border: 1px solid #555;
}}
button.secondary:hover {{ background: #2a2a2a; }}
.submit-note {{
    color: #bbb;
    font-size: 0.9rem;
    margin-top: 0.75rem;
    font-style: italic;
}}
</style>
</head>
<body>
<h1>Finding Your Neighborhood</h1>
<p>Create a simple static door site. The site will describe the space, then point people toward the places connection already happens.</p>
{editing_notice}
<form method="POST">

<div class="section">
<h2>Your Door</h2>

<label>What is this space called?</label>
<p class="help">Example: Amur Tiger SSP Resources</p>
<input name="site_title" value="{site_title}" required>

<label>Who is this for?</label>
<p class="help">One sentence. Example: People working on or following Amur tiger conservation across AZA institutions.</p>
<textarea name="site_description" required>{site_description}</textarea>

<label>How should this door look?</label>
<p class="help">Dark is quieter. Light is warmer. Both work. You can change this later by rebuilding.</p>
<div style="display: flex; gap: 1.5rem; margin-top: 0.5rem;">
    <label style="font-weight: normal; display: flex; align-items: center; gap: 0.5rem; cursor: pointer;">
        <input type="radio" name="theme" value="dark" {dark_checked}> Dark
    </label>
    <label style="font-weight: normal; display: flex; align-items: center; gap: 0.5rem; cursor: pointer;">
        <input type="radio" name="theme" value="light" {light_checked}> Light
    </label>
</div>
</div>

<div class="section">
<h2>This Place</h2>

<label>One sentence intro</label>
<p class="help">Example: A public-facing door for Amur tiger conservation resources.</p>
<textarea name="home_intro" required>{home_intro}</textarea>

<label>Describe this space</label>
<p class="help">A short paragraph. What should someone understand when they arrive here?</p>
<textarea name="home_body" required>{home_body}</textarea>
</div>

<div class="section">
<h2>Where People Should Go</h2>
<p class="help">Add two or three real places people should go next — a subreddit, Discord, organization page, newsletter, or existing website. FYN points toward connection. It doesn't become it.</p>

<div id="links-container">
{link_blocks}
</div>

<button type="button" class="secondary" id="add-link">Add another place</button>
</div>

<div class="section">
<button type="submit">{"Rebuild My Door" if existing else "Create My Door"}</button>
<p class="submit-note">This will {"rebuild" if existing else "build"} a folder of static files ready to publish to GitHub Pages.</p>
</div>

</form>

<script>
let linkCount = {num_links};
document.getElementById('add-link').addEventListener('click', function() {{
    linkCount++;
    const container = document.getElementById('links-container');
    const block = document.createElement('div');
    block.className = 'link-block';
    block.innerHTML = `
        <h3>Place ${{linkCount}}</h3>
        <label>What is this place?</label>
        <input type="text" name="link_label_${{linkCount}}">
        <label>Where can someone find it?</label>
        <input type="url" name="link_url_${{linkCount}}">
        <label>Why would someone go here?</label>
        <textarea name="link_desc_${{linkCount}}"></textarea>
        <button type="button" class="secondary remove-link" style="margin-top:0.5rem;">Remove this place</button>
    `;
    container.appendChild(block);
    block.querySelector('.remove-link').addEventListener('click', function() {{
        block.remove();
    }});
}});
// Wire up remove buttons on existing blocks
document.querySelectorAll('.remove-link').forEach(function(btn) {{
    btn.addEventListener('click', function() {{
        btn.closest('.link-block').remove();
    }});
}});
</script>
</body>
</html>"""


def open_preview(preview_path):
    """Open the preview in a browser. Cross-platform."""
    uri = Path(preview_path).resolve().as_uri()
    try:
        if sys.platform == "win32":
            import subprocess as sp
            try:
                sp.run(["cmd", "/c", "start", "chrome", uri], check=True)
            except Exception:
                webbrowser.open(uri)
        else:
            webbrowser.open(uri)
    except Exception:
        # If browser launch fails entirely, the success page shows the path.
        pass


class Handler(BaseHTTPRequestHandler):

    def log_message(self, format, *args):
        # Suppress default request logging to keep console clean.
        pass

    def do_GET(self):
        existing = load_existing_config()
        self.respond(build_form_html(existing))

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(length).decode("utf-8")
        data = parse_qs(raw)

        def get(name):
            return data.get(name, [""])[0].strip()

        # Collect links — clean loop with single exit condition.
        links = []
        for i in range(1, 21):
            label = get(f"link_label_{i}")
            url = get(f"link_url_{i}")
            desc = get(f"link_desc_{i}")
            if label and url:
                links.append({
                    "label": label,
                    "url": url,
                    "description": desc,
                    "type": "Place to go"
                })

        config = {
            "site": {
                "title": get("site_title"),
                "description": get("site_description"),
                "theme": get("theme") if get("theme") in ("light", "dark") else "dark"
            },
            "pages": [
                {
                    "slug": "index",
                    "title": "Home",
                    "intro": get("home_intro"),
                    "body": [get("home_body")]
                },
                {
                    "slug": "links",
                    "title": "Where People Should Go",
                    "intro": "Creator-defined places and resources.",
                    "body": [
                        "These places are chosen by the site creator. "
                        "FYN does not maintain a directory or infer relationships between communities."
                    ],
                    "link_groups": [
                        {
                            "title": "Places to go next",
                            "links": links
                        }
                    ]
                }
            ]
        }

        with open("config.json", "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2)

        try:
            subprocess.run(
                [sys.executable, "build.py"],
                check=True
            )
            preview_path = str(Path("docs") / "index.html")
            threading.Thread(
                target=open_preview,
                args=(preview_path,),
                daemon=True
            ).start()
            self.respond(SUCCESS_HTML.format(preview_path=preview_path))
        except subprocess.CalledProcessError as exc:
            self.respond(f"""
            <html>
            <body style="font-family: Georgia; padding: 2rem; background: #111; color: #eee;">
            <h1 style="color: #c9a84c;">Build failed.</h1>
            <p>Something went wrong during the build. Check the terminal for details.</p>
            <pre style="background: #181818; padding: 1rem; color: #bbb;">{exc}</pre>
            </body>
            </html>
            """)
            return

        threading.Thread(target=self.server.shutdown, daemon=True).start()

    def respond(self, html):
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.end_headers()
        self.wfile.write(html.encode("utf-8"))


def open_browser():
    time.sleep(1.5)
    webbrowser.open(f"http://localhost:{PORT}")


def main():
    server = HTTPServer(("localhost", PORT), Handler)
    print(f"Finding Your Neighborhood")
    print(f"Creator running at http://localhost:{PORT}")
    print(f"Opening in browser...")
    threading.Thread(target=open_browser, daemon=True).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        server.server_close()


if __name__ == "__main__":
    main()
